# Generated by Django 3.1.7 on 2021-05-14 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PastEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('location', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=500)),
                ('main_image', models.ImageField(default='', upload_to='web/images')),
            ],
        ),
        migrations.CreateModel(
            name='SubscribedMail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='UpcomingEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('location', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=500)),
                ('main_image', models.ImageField(default='', upload_to='web/images')),
            ],
        ),
        migrations.CreateModel(
            name='UserQuery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('email', models.EmailField(max_length=254)),
                ('contact', models.CharField(max_length=13)),
                ('query', models.CharField(choices=[('CU', 'Contact Us'), ('SU', 'Suggest Us'), ('VU', 'Volunteer With Us')], max_length=2)),
                ('comments', models.TextField()),
                ('subscribe_to_mail', models.BooleanField()),
                ('subscribe_to_whatsapp', models.BooleanField()),
            ],
        ),
    ]
