# Generated by Django 3.1.7 on 2021-05-14 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pastevent',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='upcomingevent',
            name='description',
            field=models.TextField(),
        ),
    ]
